### ISSUE TITLE
Components List

### ISSUE THREAD

**Issue by AbdurrahmanSogbesan** [AbdurrahmanSogbesan/chat-page#1]
@hmoskva List of components : 
- Sidebar
- Sidebar List Items
- Sidebar List Item
- Create Chat Button
- Search Text Box
- Messages Select Box
- Chat Preview Box
- Attachment (in chat preview)
- Text Number
- Individual Chat Box
- Chat header
- Text Box
- Chat Buttons (attach files etc)
- All Icons

**Comment by hmoskva** [comment]
> @hmoskva List of components :
> 
> * Sidebar
> * Sidebar List Items
> * Sidebar List Item
> * Create Chat Button
> * Search Text Box
> * Messages Select Box
> * Chat Preview Box
> * Attachment (in chat preview)
> * Text Number
> * Individual Chat Box
> * Chat header
> * Text Box
> * Chat Buttons (attach files etc)
> * All Icons

@AbdurrahmanSogbesan looks good. Just change following;
1. 'Create Chat Button' to just 'Button'
2. 'Search Text Box' to just 'Text Box'
3. 'Messages Select Box' to just 'Dropdown'
4. 'Chat Preview Box' to 'ChatCard'
5. 'Attachment (in chat preview)' to be 'AttachmentCard'
6. 'Individual Chat Box' to 'MessageCard'

In addition, add following components:
1. MessagerInfo: The component that houses these details - the picture, name and some stuff below as in these images;
<img width="234" alt="Screenshot 2020-12-22 at 00 29 34" src="https://user-images.githubusercontent.com/32783131/102831793-e64bc400-43ec-11eb-9a05-4cde74bdb3c5.png">
<img width="234" alt="Screenshot 2020-12-22 at 00 29 27" src="https://user-images.githubusercontent.com/32783131/102831800-e9df4b00-43ec-11eb-85c7-448905295b01.png">
<img width="234" alt="Screenshot 2020-12-22 at 00 29 20" src="https://user-images.githubusercontent.com/32783131/102831801-ea77e180-43ec-11eb-912c-fc96b06346e9.png">
<img width="234" alt="Screenshot 2020-12-22 at 00 28 48" src="https://user-images.githubusercontent.com/32783131/102831803-eb107800-43ec-11eb-8481-d005773f2a53.png">

2. Icon - This is the one thatll have the round purple that you now pass the svg into
